Fix parsing embedded bitmap resources
nanoframework/nf-Visual-Studio-extension pull request #729
Opened 2022-08-01 07:32 UTC by TerryFogg

## Description
This adds the "GetBitmap" from a resource file.
This code has been available but due to incorrect identification of resource kind was not working.

## Motivation and Context
Fixes a problem with bitmap resources.

## How Has This Been Tested?
From an nf C# program add a nf Resource file.
Add Bitmaps of any type to the resource file.
Check that an entry in the resource file designer code has a new GetBitmap(...) and resource id in the file.

## Screenshots

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (add new Unit Test(s) or improved existing one(s), has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:
- [x] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).
- [ ] I have added new tests to cover my changes.

2022-08-01 07:32 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/nanoframework/nf-Visual-Studio-extension?pullRequest=729) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/nanoframework/nf-Visual-Studio-extension?pullRequest=729) before we can accept your contribution.<br/><br/>:x: TerryFogg [sign now](https://cla.dotnetfoundation.org/nanoframework/nf-Visual-Studio-extension?pullRequest=729)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/nanoframework/nf-Visual-Studio-extension?pullRequest=729) it.</sub>

2022-08-01 18:38 UTC, josesimoes requested changes

2022-08-01 18:38 UTC, josesimoes commented on Tools.BuildTasks-2019/ProcessResourceFiles.cs
> +            private byte[] GetBitmapDataBmp(Bitmap bitmap, out NanoResourceFile.CLR_GFX_BitmapDescription bitmapDescription)
Noted about this. Please remove the comment.

2022-08-01 18:38 UTC, josesimoes commented on Tools.BuildTasks-2019/ProcessResourceFiles.cs
> +                        } // Ignore error if not a bitmap
comment inside catch block please

2022-08-01 18:38 UTC, josesimoes commented on Tools.BuildTasks-2019/ProcessResourceFiles.cs
> +                string nameOfResourceType = value.GetType().Name;
what is the purpose of this string here?

2022-08-01 18:38 UTC, josesimoes commented on Tools.BuildTasks-2019/ProcessResourceFiles.cs
> +                    case "String":
please split the various "case" with an empty line

2022-08-01 18:38 UTC, josesimoes commented on Tools.BuildTasks-2019/ProcessResourceFiles.cs
> +                    byte[] data = new byte[clone.Width * clone.Height * 2]; // 2 bytes per pixel
comment before code line please

2022-08-02 12:59 UTC, josesimoes approved these changes
LGTM!

2022-08-02 13:02 UTC, merged